trigger:
- main

pr: none

#variables:
#- group: Variable-Group
#- group: Key-Vault-Group

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |
        echo "Building container.."
        docker build -t registry.$(BASE-DOMAIN)/$(RELEASE-NAME)/airflow:$(Build.SourceVersion) .
        docker login registry.$(BASE-DOMAIN) -u _ -p $(SVC-ACCT-KEY)
        docker push registry.$(BASE-DOMAIN)/$(RELEASE-NAME)/airflow:$(Build.SourceVersion)