trigger:
- main

pr: none

#variables:
#- group: Variable-Group
#- group: Key-Vault-Group

stages:
- stage: deploy
  jobs:
  - job: deploy_image
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy
