trigger:
- main

# variables:
#  group: Variable-Group
# - group: Key-Vault-Group

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |
    echo "Building container.."
    docker build -t registry.aws.solutions.astronomer-sandbox.io/meteoroidal-ecliptic-6881/airflow:$CI_PIPELINE_ID .
    docker login registry.aws.solutions.astronomer-sandbox.io -u _ -p $DEPLOYMENT_SERVICE_ACCOUNT_KEY
    docker push registry.aws.solutions.astronomer-sandbox.io/meteoroidal-ecliptic-6881/airflow:$CI_PIPELINE_ID

